Added Support for Java
code100x/algorithmic-arena pull request #56
Opened 2024-06-19 12:28 UTC by mohitejaikumar

fix #49

2024-06-19 12:35 UTC, mohitejaikumar commented
While execution function.java file locally change name of file to Main.java .

2024-06-19 14:23 UTC, SujithThirumalaisamy commented on apps/problems/max-element/boilerplate-full/function.java
> +    public static void main(String[] args) {
The file path seems wrong. Can you make this like the other files do. It should be something like `/dev/problems`
That is the place where the problems are mounted

2024-06-19 14:25 UTC, SujithThirumalaisamy commented on apps/boilerplate-generator/src/FullProblemDefinitionGenerator.ts
> +        String filePath = "/WebDevelopment/algorithmic-arena/apps/problems/${this.problemName.toLowerCase().replace(" ", "-")}/tests/inputs/##INPUT_FILE_INDEX##.txt";
Expected: `/dev/problems/${this.problemName.toLowerCase().replace(" ", "-")}/tests/inputs/##INPUT_FILE_INDEX##.txt`

2024-06-19 15:40 UTC, mohitejaikumar commented on apps/boilerplate-generator/src/FullProblemDefinitionGenerator.ts
> +        String filePath = "/WebDevelopment/algorithmic-arena/apps/problems/${this.problemName.toLowerCase().replace(" ", "-")}/tests/inputs/##INPUT_FILE_INDEX##.txt";
oh sorry , actually it was for local development ,
Changed it you can review

2024-06-19 15:47 UTC, mohitejaikumar commented
Resolved some bug in generateCpp() of ProblemDefinationGenerator

2024-06-19 16:29 UTC, siinghd requested changes
Other than these small things looks fine

2024-06-19 16:29 UTC, siinghd commented on apps/problems/classroom/boilerplate-full/function.java
> +        String filePath = "/WebDevelopment/algorithmic-arena/apps/problems/classroom/tests/inputs/##INPUT_FILE_INDEX##.txt";
as suggest by @SujithThirumalaisamy this should be same as others

2024-06-19 16:29 UTC, siinghd commented on apps/problems/max-element/boilerplate-full/function.java
> +        String filePath = "/WebDevelopment/algorithmic-arena/apps/problems/max-element/tests/inputs/##INPUT_FILE_INDEX##.txt";
same here

2024-06-19 16:29 UTC, siinghd commented on apps/problems/two-sum/boilerplate-full/function.java
> +        String filePath = "/WebDevelopment/algorithmic-arena/apps/problems/two-sum/tests/inputs/##INPUT_FILE_INDEX##.txt";
same here

2024-06-19 21:58 UTC, merged

2024-06-20 05:43 UTC, mohitejaikumar commented
Is there any bounty for this @hkirat

2024-06-20 13:46 UTC, mohitejaikumar commented
is there any bounty for this @siinghd

2024-06-21 00:01 UTC, hkirat commented
There would be one but we're giving them out together now at end of month after testing the issue
it'll prolly be ~$20